server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: euModule
        uri: lb://EU-GRAPHQL-SERVICE #Service name in the service registry
        predicates:
        - Path=/eu/**
      - id: usaModule
        uri: lb://USA-GRAPHQL-SERVICE
        predicates:
        - Path=/usa/**
      loadbalancer:
        ribbon:
          enabled: true