server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: euModule
        uri: lb://EU-SERVICE #Service name in the service registry
        predicates:
        - Path=/eu/**
      - id: usaModule
        uri: lb://USA-SERVICE
        predicates:
        - Path=/usa/**
      - id: chinaModule
        uri: lb://CHINA-SERVICE
        predicates:
        - Path=/china/**
      loadbalancer:
        ribbon:
          enabled: true